### PR TITLE
Handle rank sometimes being sent as empty string

### PR DESCRIPTION
**Pull request by DnlLrssn**
**Checklist**

- [ ] tests added
- [ ] commits conform to the [Commit message format](https://github.com/qlik-oss/gopherciser/blob/master/.github/CONTRIBUTING.md#commit)
- [ ] documentation updated

**Squash commit message**

Handle rank sometimes being sent as empty string.

**Info**

Optional informative text (not to be included in commit message) relevant to reviewers.

### CODE REVIEW

**Review by foh79 — APPROVED** [review]
LGTM

**Review by atluq — APPROVED** [review]
Nice, looks good!

Not objectively for better or worse, I would probably have done the cast at the time of Unmarshal.

**Comment by DnlLrssn** [comment]
> 
> 
> Not objectively for better or worse, I would probably have done the cast at the time of Unmarshal.

I would normally too, but the type SheetListcurrently doesn't have an unmarshal interface implemented, and didn't want to add one just for this.

**Comment by atluq** [comment]
> > Not objectively for better or worse, I would probably have done the cast at the time of Unmarshal.

The rank-value comes from raw json Unmarshaled to SheetListLayout, so it doesn't seem to be to much work. Adding a custom float64 type and implement Unmarshal.

**Comment by DnlLrssn** [comment]
true a custom float64 might have looked a little better,

**Pull request merged**
