### PR TITLE
log feature flag info row

### PR DESCRIPTION
**Pull request by DnlLrssn**
**Checklist**

- [ ] tests added
- [x] commits conform to the [Commit message format](https://github.com/qlik-oss/gopherciser/blob/master/.github/CONTRIBUTING.md#commit)
- [ ] documentation updated

**Squash commit message**

Add info row log with current feature flags.

**Info**

Optional informative text (not to be included in commit message) relevant to reviewers.

### CODE REVIEW

**Review by SeBBBe — APPROVED** [review]
How often will it run?

**Comment by DnlLrssn** [comment]
> 
> 
> How often will it run?

once per openhub action. I.e. most likely once per user simulated for most scripts (unless multiple openhub actions in script)

**Comment by DnlLrssn** [comment]
> 
> 
> How often will it run?

and now, only once

**Review by atluq — APPROVED** [review]
Looks good 👍

Could be an idea to use sync.Once, but the FeatureFlagsLogged bool is already synchronized by the mutex in Features.

**Comment by DnlLrssn** [comment]
> 
> 
> Looks good 👍
> 
> Could be an idea to use sync.Once, but the FeatureFlagsLogged bool is already synchronized by the mutex in Features.

sure, not super important if it's truly once though, just that we don't spam it when haven 10's of k's of users.

**Comment by SeBBBe** [comment]
I think any performance impact of sync.Once is negligible once it's been run once, as it's basically just checking an atomic boolean. Actually like the idea suggested by Anton to use it in case we have many users with each opening the hub.

> sync.Once() has an "optimized", short path that uses only an atomic load to check if the task has been called before, and if so, no mutex is used.

https://stackoverflow.com/questions/53376237/efficiency-measurments-of-gos-once-type

**Comment by DnlLrssn** [comment]
> 
> 
> I think any performance impact of sync.Once is negligible once it's been run once, as it's basically just checking an atomic boolean. Actually like the idea suggested by Anton to use it in case we have many users with each opening the hub.
> 
> > sync.Once() has an "optimized", short path that uses only an atomic load to check if the task has been called before, and if so, no mutex is used.
> 
> https://stackoverflow.com/questions/53376237/efficiency-measurments-of-gos-once-type

Don't think we can expect that many users to hit this part of the code all at once, and if a few do, I see logging a few rows with same info as not an issue. I can add it, just saw it as a bad practice in principle to add unnecessary sync between separate users.

**Pull request merged**
