### PR TITLE
Apicompliance/616 Openhub

### PR DESCRIPTION
**Pull request by alfinhaji**
**Checklist**

- [ ] tests added
- [x] commits conform to the [Commit message format](./CONTRIBUTING.md#commit)
- [ ] documentation updated

**Squash commit message**

Several API calls have been updated from limit=30 to limit=24, as well several new additional API calls, as a part of QCS elasticopenhub action.

### CODE REVIEW

**Comment by alfinhaji** [comment]
I built both oss and trial versions with this change so far and both built and were able to run elasticopenhub successfully, and validated the API changes with traffic logs

**Comment by DnlLrssn** [comment]
> 
> 
> @DnlLrssn I do need assistance on capturing the data connection ID in the response for the new dc-dataconnections API call. Need to parse response and get the "id" for "qName": "DataFiles" which is then used in the subsequent /api/v1/qix-datafiles?top=1000&connectionId=xxxx call (which I have commented out for now)

There seems to be 24 hits with `"qName": "DataFiles"` when I check my case, so qName is not the selector, needs to be something else. will try to find out.

**Comment by DnlLrssn** [comment]
ok seems to be close to what it is actually. 
it's `"qName": "DataFiles"` without a `space` parameter

**Comment by DnlLrssn** [comment]
Added the data struct as `elasticstructs/datafilesresponse.go`, wasn't sure if you wanted to try yourself to add the logic too use it.

**Comment by DnlLrssn** [comment]
changes so far lgtm.

**Comment by DnlLrssn** [comment]
also merged latest master into the branch to make build pass

**Comment by alfinhaji** [comment]
Tested both oss and internal, with and without jwtlogin action, and with both tenant admin and test users, passed all this testing.

**Pull request merged**
