### PR TITLE
Remove logging of session ID.

### PR DESCRIPTION
**Pull request by DnlLrssn**
**Checklist**

- [ ] tests added
- [x] commits conform to the [Commit message format](https://github.com/qlik-oss/gopherciser/blob/master/.github/CONTRIBUTING.md#commit)
- [ ] documentation updated

**Squash commit message**

Remove session name from log entries.

**Info**

Optional informative text (not to be included in commit message) relevant to reviewers.

### CODE REVIEW

**Review by atluq — COMMENTED** [review]
Shall we remove the SessionName field from SessionEntry struct or give it a value from another source?

**Comment by SeBBBe** [comment]
It will still log a column though? The AllFields that's passed in to CreateTSVLogger remains unchanged.

**Comment by atluq** [comment]
> Shall we remove the SessionName field from SessionEntry struct or give it a value from another source?

Removing it would probably break a few pipelines, so I see why it is kept.

**Review by atluq — APPROVED** [review]

**Comment by DnlLrssn** [comment]
> 
> 
> > Shall we remove the SessionName field from SessionEntry struct or give it a value from another source?
> 
> Removing it would probably break a few pipelines, so I see why it is kept.

It would break sense loadscripts defining this column, so that's the exact reason why it's still there.

**Comment by SeBBBe** [comment]
Then why even make this change though? If the session id is salted it could still be used as a unique key, theoretically.

**Comment by DnlLrssn** [comment]
> 
> 
> Then why even make this change though? If the session id is salted it could still be used as a unique key, theoretically.

yes, but we'd have to get the salt and hash it. And then we need to know if it's QSEoW to know if we can send requests to figure out the salt, which would be a lot more code changes has this part of the code has no clue what kind of environment we are connecting to, it could be QSEoK, QSEoW, Qlik Core etc etc. Would also need to start mixing in REST requests into the websocket connect logic which I'm not very keen on either.

**Pull request merged**
