### PR TITLE
add /debug/pprof endpoint when running tool with --metrics flag

### PR DESCRIPTION
**Pull request by DnlLrssn**
**Checklist**

- [ ] tests added
- [x] commits conform to the [Commit message format](https://github.com/qlik-oss/gopherciser/blob/master/.github/CONTRIBUTING.md#commit)
- [ ] documentation updated

**Squash commit message**

Add /debug/pprof endpoint to tool when running a http listener (currrently done with the --metrics flag) for debugging purposes. Should not affect anything other then slightly bigger binary unless listener is running and endpoint accessed.

**Info**

Optional informative text (not to be included in commit message) relevant to reviewers.

### CODE REVIEW

**Review by SeBBBe — APPROVED** [review]
It just terminates if there is no web server?

**Comment by DnlLrssn** [comment]
> 
> 
> It just terminates if there is no web server?

Has far as I could understand it should not do any profiling unless the endpoint is called, i.e. with no webserver shouldn't impact. The import has an init which registers some handlers to default https muxer. (unfortunatly no way to avoid having that init run). And to my understanding shouldn't be run. TBH couldn't conclusively  find this to be the case, hence the use of the word "should".

**Comment by DnlLrssn** [comment]
calls are e.g. 
http://localhost:[metricsport]/debug/pprof/profile?seconds=30 to do 30s CPU profile

**Comment by SeBBBe** [comment]
That's the impression I got as well from a quick googling. Just wanted to make sure that it won't kick off any profiling when running normally.

**Review by atluq — APPROVED** [review]
LGTM!

**Pull request merged**
